swagger: '2.0'
info:
  version: 0.0.0
  title: CT and JIRA hours checker
paths:
  /:
    get:
      summary:
        Returns an html page with a description of what the JIRA/CurrentTime checker is about, and links
        to the cvs-links.
      produces:
        - text/html
      responses:
        200:
          description: OK

  /compare-totals.csv:
    get:
      summary:
        Returns a CSV-file that displays the differences between the total number of hours logged in JIRA and the
        total number of hours logged in CurrentTime.
      produces:
        - text/csv
      responses:
        200:
          description: OK

  /currenttime-with-jira-keys.csv:
    get:
      summary:
        Returns a CSV-file that displays problems with CurrentTime entries that refer to JIRA-issues
        in the "Note" field.
      produces:
        - text/csv
      responses:
        200:
          description: OK
